import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Default Title",
    template: "%s | Company Name",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Error in LayoutRouter.tsx
  const randId = Math.floor(Math.random() * 2);
  console.log(randId);

  if (randId === 0) {
    throw new Error("No.0 Blog is not available!");
  }

  return (
    <html lang="en">
      <header>
        <h1 className="text-2xl bg-yellow-100 text-black">Header</h1>
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <footer>
        <h1>Footer</h1>
      </footer>
    </html>
  );
}
